learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learning_logs.urls')),
]

learning_logs/urls.py
"""定义learning_logs的URL模式"""
from django.urls import path
from . import views

app_name = 'learning_logs'
urlpatterns = [
    # 主页
    path('', views.index, name='index'),
    # 显示所有的主题
    path('topics/', views.topics, name='topics'),
    # 显示特定主题的详细页面
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # 用于添加新主题的页面
    path('new_topic/', views.new_topic, name='new_topic'),
    # 用于添加新条目的页面
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    #用于编辑条目的页面
    path('edit_entry/<int:entry_id>/',views.edit_entry,name='edit_entry'),
    #用于添加middle条目的页面
    path('new_entry_middle/<int:topic_id>/',views.new_entry_middle,name='new_entry_middle'),
    #用于添加end条目的页面
    path('new_entry_end/<int:topic_id>/',views.new_entry_end,name='new_entry_end'),
    # 用于编辑middle条目的页面
    path('edit_entry_middle/<int:entry_id>/', views.edit_entry_middle, name='edit_entry_middle'),
    # 用于编辑end条目的页面
    path('edit_entry_end/<int:entry_id>/', views.edit_entry_end, name='edit_entry_end'),
]

users/urls.py
"""为应用程序users定义URL模式"""
from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    # 包含默认的身份验证URL
    path('', include('django.contrib.auth.urls')),
    #注册页面
    path('register/',views.register,name='register'),
]

learning_logs/forms.py
from django import forms
from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text', 'key_days', 'last_retention', 'rating_5', 'rating_4', 'rating_3', 'rating_2', 'rating_1',
                  'rating_average',
                  'positive_percent']
        labels = {'text': '请输入日期等相关文本信息：',
                  'key_days': '月初：',
                  'last_retention': '请输入前一天的真实用户留存率：（0～1） 如0.381',
                  'rating_5': '请输入当天五星级占比：（0～1） 如0.53333',
                  'rating_4': '请输入当天四星级占比：（0～1） 如0.53333',
                  'rating_3': '请输入当天三星级占比：（0～1） 如0.53333',
                  'rating_2': '请输入当天二星级占比：（0～1） 如0.53333',
                  'rating_1': '请输入当天一星级占比：（0～1） 如0.53333',
                  'rating_average': '请输入当天星级平均得分：（0～5） 如4.35',
                  'positive_percent': '请输入当天用户评论积极程度占比：（0～1） 如0.53333',
                  }
        # widgets = {'text': forms.Textarea(attrs={'cols': 80}),
        #            'key_days': forms.IntegerField(max_value=30,min_value=1),
        #            'rating_5': forms.DecimalField(max_digits=11,decimal_places=10),
        #            'rating_4': forms.DecimalField(max_digits=11,decimal_places=10),
        #            'rating_3': forms.DecimalField(max_digits=11,decimal_places=10),
        #            'rating_2': forms.DecimalField(max_digits=11,decimal_places=10),
        #            'rating_1': forms.DecimalField(max_digits=11,decimal_places=10),
        #            'rating_average': forms.DecimalField(max_digits=11,decimal_places=10),
        #            'positive_percent': forms.DecimalField(max_digits=11,decimal_places=10),
        #            }


class EntryMiddleForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text', 'key_days_middle', 'retention_1_middle', 'retention_2_middle', 'retention_3_middle', 'retention_4_middle', 'retention_5_middle',
                  'retention_6_middle', 'retention_7_middle']
        labels = {'text': '请输入日期等相关文本信息：',
                  'key_days_middle': '月中：',
                  'retention_1_middle': '请输入第一天的真实用户留存率：（0～1） 如0.381',
                  'retention_2_middle': '请输入第二天的真实用户留存率：（0～1） 如0.381',
                  'retention_3_middle': '请输入第三天的真实用户留存率：（0～1） 如0.381',
                  'retention_4_middle': '请输入第四天的真实用户留存率：（0～1） 如0.381',
                  'retention_5_middle': '请输入第五天的真实用户留存率：（0～1） 如0.381',
                  'retention_6_middle': '请输入第六天的真实用户留存率：（0～1） 如0.381',
                  'retention_7_middle': '请输入第七天的真实用户留存率：（0～1） 如0.381',

                  }


class EntryEndForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text', 'key_days_end', 'retention_1_end', 'retention_2_end', 'retention_3_end', 'retention_4_end', 'retention_5_end',
                  'retention_6_end', 'retention_7_end', 'retention_8_end']
        labels = {'text': '请输入日期等相关文本信息：',
                  'key_days_end': '月末：',
                  'retention_1_end': '请输入第一天的真实用户留存率：（0～1） 如0.381',
                  'retention_2_end': '请输入第二天的真实用户留存率：（0～1） 如0.381',
                  'retention_3_end': '请输入第三天的真实用户留存率：（0～1） 如0.381',
                  'retention_4_end': '请输入第四天的真实用户留存率：（0～1） 如0.381',
                  'retention_5_end': '请输入第五天的真实用户留存率：（0～1） 如0.381',
                  'retention_6_end': '请输入第六天的真实用户留存率：（0～1） 如0.381',
                  'retention_7_end': '请输入第七天的真实用户留存率：（0～1） 如0.381',
                  'retention_8_end': '请输入第十四天的真实用户留存率：（0～1） 如0.381',
                  }

learning_logs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404
from .models import Topic, Entry
from .forms import TopicForm, EntryForm, EntryMiddleForm, EntryEndForm


# Create your views here.
def index(request):
    """学习笔记的主页"""
    return render(request, 'learning_logs/index.html')


@login_required
def topics(request):
    if request.method == "GET":
        search = ''
    else:
        search = request.POST.get('search')
    topics = Topic.objects.filter(owner=request.user, text__icontains=search).order_by('-date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)


@login_required
def topic(request, topic_id):
    if request.method == "GET":
        search = ''
    else:
        search = request.POST.get('search')
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.filter(text__icontains=search).order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)


@login_required
def new_topic(request):
    """添加新主题"""
    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('learning_logs:topics')
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    """在特定主题中添加新条目"""
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)


@login_required
def new_entry_middle(request, topic_id):
    """在特定主题中添加新条目"""
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST' :
        form = EntryMiddleForm()
    else:
        form = EntryMiddleForm(data=request.POST)
        if form.is_valid():
            new_entry_middle = form.save(commit=False)
            new_entry_middle.topic = topic
            new_entry_middle.save()
            return redirect('learning_logs:topic', topic_id=topic_id)
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry_middle.html', context)
@login_required
def new_entry_end(request, topic_id):
    """在特定主题中添加新条目"""
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST' :
        form = EntryEndForm()
    else:
        form = EntryEndForm(data=request.POST)
        if form.is_valid():
            new_entry_end = form.save(commit=False)
            new_entry_end.topic = topic
            new_entry_end.save()
            return redirect('learning_logs:topic', topic_id=topic_id)
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry_end.html', context)

@login_required
def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404
    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)
    content = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', content)

@login_required
def edit_entry_middle(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404
    if request.method != 'POST':
        form = EntryMiddleForm(instance=entry)
    else:
        form = EntryMiddleForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)
    content = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry_middle.html', content)

@login_required
def edit_entry_end(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404
    if request.method != 'POST':
        form = EntryEndForm(instance=entry)
    else:
        form = EntryEndForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)
    content = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry_end.html', content)

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,
        shrink-to-fit=no">
    <title>Learning Log</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light bg_light mb-4 border">
        <a class="nav-brand" href="{% url 'learning_logs:index' %}">
            Home
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarCollapse" aria-controls="navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggle-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'learning_logs:topics' %}">
                        Games
                    </a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <span class="navbar-text">
                        Hello,{{ user.username }}.
                    </span>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:logout' %}">
                        Log out
                    </a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:register' %}">
                        Register
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">
                        Log in
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>
</body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Entry</title>
</head>
<body>
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h2>Edit entry</h2>
{% endblock page_header %}
{% block content %}
  <form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% buttons %}
        <button name="submit" class="btn btn-primary">Save changes</button>
      {% endbuttons %}
  </form>
{% endblock content %}
</body>
</html>

learning_logs/templates/learning_logs/edit_entry_end.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Entry</title>
</head>
<body>
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h2>Edit end entry</h2>
{% endblock page_header %}
{% block content %}
  <form action="{% url 'learning_logs:edit_entry_end' entry.id %}" method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% buttons %}
        <button name="submit" class="btn btn-primary">Save changes</button>
      {% endbuttons %}
  </form>
{% endblock content %}
</body>
</html>

learning_logs/templates/learning_logs/edit_entry_middle.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Entry</title>
</head>
<body>
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h2>Edit middle entry</h2>
{% endblock page_header %}
{% block content %}
  <form action="{% url 'learning_logs:edit_entry_middle' entry.id %}" method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% buttons %}
        <button name="submit" class="btn btn-primary">Save changes</button>
      {% endbuttons %}
  </form>
{% endblock content %}
</body>
</html>

learning_logs/templates/learning_logs/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body>
{% extends "learning_logs/base.html" %}

{% block page_header %}
    <div class="jumbotron">
        <h1 class="display-3">
            Track your games.
        </h1>
        <p class="lead">
            Make your own Game Log, and keep a list of the
            games you're tracking about. Whenver you track something new
            about a game, make an entry summarizing what you've tracked.
        </p>
        <a class="btn btn-lg btn-primary" href="{% url 'learning_logs:topics' %}" role="button">
            Let's Go &raquo;
        </a>
    </div>
{% endblock page_header %}
</body>
</html>

learning_logs/templates/learning_logs/new_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New Entry</title>
</head>
<body>
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h2>Add a new entry</h2>
{% endblock page_header %}
{% block content %}
  <form action="{% url 'learning_logs:new_entry' topic.id %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button name="submit" class="btn btn-primary">Add entry</button>
    {% endbuttons %}
  </form>
{% endblock content %}
</body>
</html>

learning_logs/templates/learning_logs/new_entry_end.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New Entry</title>
</head>
<body>
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h2>Add a new end entry</h2>
{% endblock page_header %}
{% block content %}
  <form action="{% url 'learning_logs:new_entry_end' topic.id %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button name="submit" class="btn btn-primary">Add entry</button>
    {% endbuttons %}
  </form>
{% endblock content %}
</body>
</html>

learning_logs/templates/learning_logs/new_entry_middle.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New Entry</title>
</head>
<body>
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h2>Add a new middle entry</h2>
{% endblock page_header %}
{% block content %}
  <form action="{% url 'learning_logs:new_entry_middle' topic.id %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button name="submit" class="btn btn-primary">Add entry</button>
    {% endbuttons %}
  </form>
{% endblock content %}
</body>
</html>

learning_logs/templates/learning_logs/new_topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New Topic</title>
</head>
<body>
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}
{% block page_header %}
    <h1>Add a new game</h1>
{% endblock page_header %}

{% block content %}
  <form action="{% url 'learning_logs:new_topic' %}" method='post' class="form">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% buttons %}
        <button name="submit" class="btn btn-primary">Add game</button>
      {% endbuttons %}
  </form>
{% endblock content %}
</body>
</html>

learning_logs/templates/learning_logs/topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Topic</title>
</head>
<body>
{% extends 'learning_logs/base.html' %}

{% block page_header %}
  <h3>{{ topic }}</h3>
{% endblock page_header %}

{% block content %}
  <p>
    <a class="btn btn-lg btn-primary" href="{% url 'learning_logs:new_entry' topic.id %}" role="button">Add new BEGIN entry</a>
    <a class="btn btn-lg btn-primary" href="{% url 'learning_logs:new_entry_middle' topic.id %}" role="button">Add new MIDDLE entry</a>
    <a class="btn btn-lg btn-primary" href="{% url 'learning_logs:new_entry_end' topic.id %}" role="button">Add new END entry</a>
  </p>
<form action="{% url 'learning_logs:topic' topic.id %}" method="post" class="form">
        {% csrf_token %}
        <input type="text" name="search" class="form-control mb-4" placeholder="在这里检索您的条目...">
</form>

    {% for entry in entries %}
    {% if entry.key_days == '0' and entry.key_days_middle == '0' and entry.key_days_end == '0' %}
    <div class="card mb-3">
      <h4 class="card-header">
        {{ entry.date_added|date:'Y-m-d   ,  H:i' }}
        <small>
          <a href="{% url 'learning_logs:edit_entry' entry.id %}">
            Edit now &raquo;
          </a>
        </small>
      </h4>
      <div class="card-body">
        <h5>
          Text:
        </h5>
          Please select the correct prediction time!
      </div>
    </div>
    {% elif entry.key_days_middle != 'Middle' and entry.key_days_end != 'End' %}
    <div class="card mb-3">
      <h4 class="card-header">
        {{ entry.date_added|date:'Y-m-d   ,  H:i' }}
        <small>
          <a href="{% url 'learning_logs:edit_entry' entry.id %}">
            Edit now &raquo;
          </a>
        </small>
      </h4>
      <div class="card-body">
        <h5>
          Text:
        </h5>
          {{ entry.text|linebreaks }}
        <h5>
          Days:
        </h5>
          {{ entry.key_days|linebreaks }}
        <h5>
          User retention:
        </h5>
          {{ entry.user_retention|linebreaks }}
      </div>
    </div>

    {% elif entry.key_days_middle == 'Middle' %}

        <div class="card mb-3">
      <h4 class="card-header">
        {{ entry.date_added|date:'Y-m-d   ,  H:i' }}
        <small>
          <a href="{% url 'learning_logs:edit_entry_middle' entry.id %}">
            Edit now &raquo;
          </a>
        </small>
      </h4>
      <div class="card-body">
        <h5>
          Text:
        </h5>
          {{ entry.text|linebreaks }}
        <h5>
          Days:
        </h5>
          {{ entry.key_days_middle|linebreaks }}
        <h5>
          User retention:
        </h5>
          {{ entry.user_retention_middle|linebreaks }}
      </div>
    </div>
    {% elif entry.key_days_end == 'End' %}

        <div class="card mb-3">
      <h4 class="card-header">
        {{ entry.date_added|date:'Y-m-d   ,  H:i' }}
        <small>
          <a href="{% url 'learning_logs:edit_entry_end' entry.id %}">
            Edit now &raquo;
          </a>
        </small>
      </h4>
      <div class="card-body">
        <h5>
          Text:
        </h5>
          {{ entry.text|linebreaks }}
        <h5>
          Days:
        </h5>
          {{ entry.key_days_end|linebreaks }}
        <h5>
          User retention:
        </h5>
          {{ entry.user_retention_end|linebreaks }}
      </div>
    </div>


    {% endif %}

    {% empty %}
      <p>There are no entries for this topic yet.</p>
    {% endfor %}
{% endblock content %}
</body>
</html>

learning_logs/templates/learning_logs/topics.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Topics</title>
</head>
<body>
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}
{% block page_header %}
    <h1>
        Games Lists
    </h1>
{% endblock page_header %}

{% block content %}
<ul>

</ul>
<p>
    <a class="btn btn-lg btn-primary" href="{% url 'learning_logs:new_topic' %}" role="button">Add a new game</a>
</p>

<form action="{% url 'learning_logs:topics' %}" method="post" class="form">
        {% csrf_token %}
        <input type="text" name="search" class="form-control mb-4" placeholder="在这里检索您的游戏...">
</form>

{% for topic in topics %}
    <div class="card mb-3">
        <h4 class="card-header">
            <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
            <small class="navbar-nav mul-auto">{{ topic.date_added|date:'Y-m-d   ,  H:i' }}</small>
        </h4>
    </div>
{% empty %}
<h3>
    No topics have been added yet.
</h3>
{% endfor %}
{% endblock content %}
</body>
</html>